### ISSUE TITLE
Change parallax image

### ISSUE THREAD

**Issue by lilTanker** [pagekit/theme-aurora#3]
I can't seem to find anywhere that I assign the image to the sidebar background. I've tried changing a bunch of image settings and nothing shows up no matter what I change. 

any pointers?

**Comment by rigelenrique** [comment]
Try navigate to Site > Settings and check out Code section there'll be header and footer code.
and add <style> tag into the header like this
```css
<style>
    .tm-sidebar-wrapper{
        background:url(https://demo.pagekit.com/theme-aurora/packages/pagekit/theme-aurora/less/uikit/images/sidebar/default.jpg);
    }
</style>
```
This will override the wrapper class and insert background image from example into your side.
